name: Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/yeelight2mqtt:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/yeelight2mqtt:latest
        target: 1
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Docker image with tag
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/yeelight2mqtt:${{ github.ref_name }}
        target: 1
        cache-from: type=gha
        cache-to: type=gha,mode=max
