name: go-latest

on:
  push:
    tags: [ '*' ]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.0
          
      - name: Download dependencies
        run: go mod download

      - name: Prepare Release Variables
        id: vars
        uses: tendermint/starport/actions/release/vars@v0.18.6

      - name: Test
        run: go test -v ./...

      - name: Cross build (gox)
        run: |
          wget https://github.com/dsorm/gox/releases/download/latest/gox_linux_amd64
          chmod +x gox_linux_amd64
          ./gox_linux_amd64 \
          -os="windows linux darwin freebsd" \
          -arch="amd64 arm64 arm ppc64 riscv64" \
          -ldflags="-w -s" -output="release/{{.Dir}}_{{.OS}}_{{.Arch}}" \
          --parallel=8
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
             $(cat changelog.md | sed '/^## /,$!d; /^## /{x;p;d}; /^## /p;d' | sed -e 's/^/  - /' | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g')
          draft: false
          prerelease: false
          
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: myapp_${{ env.GOOS }}_${{ env.GOARCH }}
          path: ./myapp_${{ env.GOOS }}_${{ env.GOARCH }}
      - name: Attach Binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./myapp_${{ env.GOOS }}_${{ env.GOARCH }}
          asset_name: myapp_${{ env.GOOS }}_${{ env.GOARCH }}
          asset_content_type: application/octet-stream
          release_id: ${{ steps.create_release.outputs.id }}
          
      - name: Create Latest Release
        id: create_latest_release
        if: startsWith(github.ref, 'refs/tags/latest')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest Release
          body: |
            $(cat changelog.md | sed '/^## /,$!d; /^## /{x;p;d}; /^## /p;d' | sed -e 's/^/  - /' | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g')
          draft: false
          prerelease: false
          
      - name: Attach Binary to Latest Release
        if: startsWith(github.ref, 'refs/tags/latest')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./myapp_${{ env.GOOS }}_${{ env.GOARCH }}
          asset_name: myapp_${{ env.GOOS }}_${{ env.GOARCH }}
          asset_content_type: application/octet-stream
          release_id: ${{ steps.create_latest_release.outputs.id }}
